# SubNav
menu:
  #å…³äºæˆ‘: /2014/aboutme/
  å‹é“¾: /2014/friends/
subnav:
  github: "https://github.com/88888888"
  weibo: "http://weibo.com/u/888888888"
  #zhihu: "https://www.zhihu.com/people/888888"
  email: "mailto:1223456@666666.com"
  sf: "https://segmentfault.com/u/555555"
  rss: "/atom.xml"

description: å¤©é©¬è¡Œç©ºï¼Œçˆ±ç”Ÿæ´»ï¼Œçˆ±coding

# SEO
seo_keywords: hexo,ä¸ªäººåšå®¢,blog
seo_description: æŸæŸçš„ä¸ªäººåšå®¢

favicon: /favicon.ico

#ä½ çš„å¤´åƒurl
avatar: https://tva3.sinaimg.cn/crop.0.0.200.200.180/005Kc3C1jw8f2uep0hhkvj305k05k3yk.jpg

# é¦–é¡µå·¦ä¾§è¾¹æ èƒŒæ™¯å›¾ç‰‡
# å¯é…ç½®å¤šä¸ª éšæœºæŒ‘é€‰ä¸€å¼ 
leftBackground:
  - https://ws3.sinaimg.cn/large/006tKfTcly1fsulzlvofnj30af0k5jvu.jpg
  - https://ws2.sinaimg.cn/large/006tNbRwly1fwl2alhqibj31kw2dcu0y.jpg
  - https://ws1.sinaimg.cn/large/006tNbRwly1fwl2bclcirj31kw2czk7v.jpg
  - https://ws3.sinaimg.cn/large/006tNbRwly1fwl2c765jej31kw2d1npe.jpg
  - https://ws3.sinaimg.cn/large/006tNbRwly1fwl2dentnvj31kw2dc1l2.jpg
  - https://ws4.sinaimg.cn/large/006tNbRwly1fwl2dqawiej31kw2d8x6p.jpg
  - https://ws3.sinaimg.cn/large/006tNbRwly1fwl2f7yp25j31kw3a97wh.jpg

# å±•ç¤ºæ›´æ–°æ—¶é—´
display_updated: true

# æ–‡ç« é¡µçš„å…³äºè½¬è½½é“¾æ¥
copyright_url: https://888.com/index.html

# åº•éƒ¨çš„å¤‡æ¡ˆä¿¡æ¯ç­‰
copyright_date: 2013-2018
beian_info: æŸæŸçš„åšå®¢ äº¬ICPå¤‡xxxxxxå·

# Online contact
daovoice: true
daovoice_app_id: 123456 #è¾“å…¥app_id

# Data statistics
baidu_analytics: true
baidu_analytics_code: awwssw1snsnsnn1ndndnndnd99j

#Comments
# https://github.com/gitalk/gitalk
gitalk: true
gitalk_clientID: 8888a8888
gitalk_clientSecret: 8888886666666
gitalk_repo: xxxx.github.io
gitalk_owner: admin
gitalk_admin: admin
# æ˜¯å¦å¯ç”¨è¯„è®ºæ¡†çš„å…¨å±é®ç½©æ•ˆæœ
gitalk_distractionFreeMode: false

# Console
console: true
console_color: '#6190e8'
console_config:
  - '\næ¬¢è¿è®¿é—® https://hufangyun.com ï¼Œå›´è§‚å°çŒ¿å¤§åœ£çš„åšå®¢(ã¥ï½¡â—•â€¿â€¿â—•ï½¡)ã¥ï¼\n'
  - '\næœ¬åšå®¢ä½¿ç”¨ %cHexo%c æ­å»ºï¼Œåšå®¢ä¸»é¢˜ä¸ºå°çŒ¿å¤§åœ£å¼€å‘çš„ %chexo-themes-yearn%c ~~~ ğŸ‰ğŸ‰ğŸ‰ \n\næºç  https://github.com/Youthink/hexo-themes-yearn \n\nå¦‚æœå–œæ¬¢å¯ä»¥ star æ”¯æŒä¸€ä¸‹ â¤ï¸~\n'
  - '\næ‰«æä¸‹é¢çš„äºŒç»´ç ï¼Œåœ¨æ‰‹æœºä¸ŠæŸ¥çœ‹åšå®¢ï¼\n'
  - 'https://static.hufangyun.com/blog-url-qrcode-180-180.png'
  - '\n æƒ³çŸ¥é“è¿™ä¸ªæ•ˆæœå¦‚ä½•å®ç°çš„ï¼Ÿåšå®¢å†…æœç´¢ console å½©è›‹ ğŸš€ ï¼\n'

